# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DemoGraphQL' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DemoGraphQL
  pod "Apollo"

  target 'DemoGraphQLTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'DemoGraphQLUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
